### ISSUE TITLE
Error in running task with excel process

### ISSUE THREAD

**Issue by arctocore** [saucepleez/taskt#73] opened 2018-10-26 06:19 UTC
Hello Jason
I make this one short. 
Version 1.8.2.0 works as it should be when running tasks when working with excel and naming it default.
I can run it again and again without getting any errors at all.

But with version 2.0.0.1 i get errors when running it more than once.

And why is your "Dropbox" mentioned in the code. 

I would really like to make use of taskt in production related work. But it is not stable yet.
Your version 1.8.2.0 works really good and i will stick to this. Until you got a more stable update.
Hope the info helped.

2018-10-26 08:08:09.293 +02:00 [INF] Engine Class has been initialized
2018-10-26 08:08:09.362 +02:00 [INF] Client requesting to execute script using frmEngine
2018-10-26 08:08:09.379 +02:00 [INF] Script Path: c:\taskt\My Scripts\Sample Scripts\Excel Activate Sheet Test.xml
2018-10-26 08:08:09.393 +02:00 [INF] Bot Engine Started: 26-10-2018 08:08:09
2018-10-26 08:08:09.408 +02:00 [INF] Deserializing File
2018-10-26 08:08:09.428 +02:00 [INF] Creating Variable List
2018-10-26 08:08:09.442 +02:00 [INF] Creating App Instance Tracking List
2018-10-26 08:08:09.457 +02:00 [INF] Running Line 1: Create Excel Application [Instance Name: 'default']
2018-10-26 08:08:10.504 +02:00 [INF] Running Line 2: Open Workbook [Open from 'c:\excel\test.xlsx', Instance Name: 'default']
2018-10-26 08:08:11.845 +02:00 [INF] Running Line 3: Activate Sheet [Sheet Name: Sheet1, Instance Name: 'default']
2018-10-26 08:08:12.115 +02:00 [INF] Result Code: Successful
2018-10-26 08:08:12.128 +02:00 [INF] Error: None
2018-10-26 08:08:24.324 +02:00 [INF] Engine Class has been initialized
2018-10-26 08:08:24.419 +02:00 [INF] Client requesting to execute script using frmEngine
2018-10-26 08:08:24.433 +02:00 [INF] Script Path: c:\My Scripts\Sample Scripts\Excel Activate Sheet Test.xml
2018-10-26 08:08:24.449 +02:00 [INF] Bot Engine Started: 26-10-2018 08:08:24
2018-10-26 08:08:24.465 +02:00 [INF] Deserializing File
2018-10-26 08:08:24.486 +02:00 [INF] Creating Variable List
2018-10-26 08:08:24.504 +02:00 [INF] Creating App Instance Tracking List
2018-10-26 08:08:24.522 +02:00 [INF] Running Line 1: Create Excel Application [Instance Name: 'default']
2018-10-26 08:08:25.561 +02:00 [INF] Result Code: Error
2018-10-26 08:08:25.574 +02:00 [INF] Error: System.Exception: System.Exception: 

> You cannot share application instance names. Ensure that Instance ID being used are unique.

   at taskt.Core.AutomationCommands.ExcelCreateApplicationCommand.RunCommand(Object sender) in 

> D:\Dropbox\Environment Folders\Documents\Visual Studio 2015\Projects\taskt\taskt\Core\AutomationCommands

.cs:line 3305
   at taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) in D:\Dropbox\Environment Folders\Documents\Visual Studio 2015\Projects\taskt\taskt\Core\AutomationEngine.cs:line 212
   at taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) in D:\Dropbox\Environment Folders\Documents\Visual Studio 2015\Projects\taskt\taskt\Core\AutomationEngine.cs:line 239
   at taskt.Core.AutomationEngineInstance.ExecuteScript(String filePath) in 

> D:\Dropbox\Environment Folders\Documents\Visual Studio 2015\Projects\taskt\taskt\Core\

AutomationEngine.cs:line

**Comment by saucepleez** [comment] 2018-10-26 11:30
Hello,

It appears that the .PDB files were bundled with the application.  When the .PDB is present it shows you the path on the build machine.  You can delete the PDB files and the stack trace should no longer show that path.  I store and sync all my user data on Dropbox, so you are seeing my local paths.

As far as Excel, that is expected behavior if you are creating two instances with the same name.  Ensure that your instances are uniquely named.  If you wish, I can make a setting for the Create Excel command that checks whether it should overwrite an existing instance - but this means you will lose control of the original instance.

As far as production ready -- yes, I think we should define a series to scripts to act as unit tests.

**Comment by saucepleez** [comment] 2018-10-26 14:38
@arctocore Thanks for bringing up this issue.  I do see a bug here, the problem is that the engine is setting app instances to be tracked by the global list.  This means once the script ends it "remembers" that instance name and is causing the issue if you run a script twice. This is so that if you leave the application open (this case Excel) after the script completes, you do not need to create a new instance again to work with the same application instance.  This was a newer feature requested for Web Browser tracking, but since all applications share the same tracking list it is affecting Excel.  It works better in previous versions because the Global Instances was not implemented and thus no impact.

Here are some bugs I found
- Excel App Instances are being tracked globally be default. Only 1 App Instance Name can exist at a time. 

- Close Excel Command does not remove the app instance from the tracking list.  This should theoretically only cause a problem if application instance is started twice in the same script.

- Instance Names currently cannot be a variable value.

- Instance names cannot be overwritten with new instances.

I will remedy these issues in DEV branch today and create thorough tests for Excel. Let me know if you need a signed binary for further testing.

I would also like to hear some thoughts on how I can better make the project "production ready" if you have any input.

**Comment by saucepleez** [comment] 2018-10-26 23:13
@arctocore  I have pushed the changes to DEV branch

**Comment by msshubin** [comment] 2018-10-27 05:29
@saucepleez thanks, now i don't need reopen Taskt when run Excel automation with same instence!

**Comment by saucepleez** [comment] 2018-10-29 15:51
Closing as it seems to be fixed.  Please re-open if you see any further issues.

**Closed** 2018-10-29 15:58 UTC
