### ISSUE TITLE
Error when open command If equal

### ISSUE THREAD

**Issue by msshubin** [saucepleez/taskt#46] opened 2018-10-08 06:59 UTC
@saucepleez today i'll pull all commits and then test my script, but have error when run:
```
2018-10-08 09:40:54.716 +03:00 [INF] Running Line 36: If ([Gender] is equal to Мужчина)
2018-10-08 09:40:54.902 +03:00 [INF] Result Code: Error
2018-10-08 09:40:54.902 +03:00 [INF] Error: System.Exception: System.Exception: System.Exception: System.ArgumentException: Строка не может иметь нулевую длину.
Имя параметра: oldValue
   в System.String.ReplaceInternal(String oldValue, String newValue)
   в System.String.Replace(String oldValue, String newValue)
   в taskt.Core.ExtensionMethods.ConvertToUserVariable(String str, Object sender) в C:\src\taskt\taskt\Core\ExtensionMethods.cs:строка 50
   в taskt.Core.AutomationCommands.BeginIfCommand.RunCommand(Object sender, ScriptAction parentCommand) в C:\src\taskt\taskt\Core\AutomationCommands.cs:строка 4140
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 192
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 231
   в taskt.Core.AutomationCommands.BeginIfCommand.RunCommand(Object sender, ScriptAction parentCommand) в C:\src\taskt\taskt\Core\AutomationCommands.cs:строка 4354
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 192
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 231
   в taskt.Core.AutomationCommands.BeginContinousLoopCommand.RunCommand(Object sender, ScriptAction parentCommand) в C:\src\taskt\taskt\Core\AutomationCommands.cs:строка 2551
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 192
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 231
   в taskt.Core.AutomationEngineInstance.ExecuteScript(String filePath) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 108
```
And when i try to change this command by double click on it, then have error too:
[error.txt](https://github.com/saucepleez/taskt/files/2454903/error.txt)

Here
![image](https://user-images.githubusercontent.com/22539710/46595395-39295180-cae9-11e8-9bae-3e3c9f84d777.png)

I'll check other If command where type is Value - same error.

**Comment by msshubin** [comment] 2018-10-08 07:52
I'll revert to and here is all ok )
https://github.com/saucepleez/taskt/commit/d3a6bb98f9ec5a30eec0abe2048817fa72c57879

**Comment by saucepleez** [comment] 2018-10-08 14:41
Hello,

The bug should be present in previous versions as well.  The editor expects only certain values can be present for if command parameters, and an empty string is not a valid value.  When you save an invalid value, that is the trigger.

I am working on a fix for this now.

**Comment by saucepleez** [comment] 2018-10-08 14:53
After reviewing further, the issue is the dropdown box was being added before the parent control was created.  Please confirm it is resolved for you in the dev branch and I will merge into master and re-release.

**Comment by msshubin** [comment] 2018-10-08 17:45
it seems to be ok

**Closed** 2018-10-11 13:05 UTC
